### ISSUE TITLE
Quests/Challenges

### ISSUE THREAD

**Issue by bennytheg** [larryTheCoder/ASkyBlock#2]
I can't seem to get quests/challenges to work, nor can I find a way to view island levels.
I was wondering whether this still actually works because I don't get notified of when a quest is completed. and if I wanted to check by using my skyblock level, I can't find where to view it. Any ideas?

**Comment by bennytheg** [comment]
This is just a question, not an issue

**Comment by larryTheCoder** [comment]
The quests and other side features are removed so that I could maintain the stability of the core first. However, the quests and others kind of features are indeed in progress on writing it, just rewrite and not the total garbage this time.

##### You can ask me other questions in my discord account, just add me as your friend, the tag is under my bio profile.

**Comment by bennytheg** [comment]
how's the progress going? My players would love the idea of racking up points and competing! Sorry if this isn't a very good place to ask, being in an "issues" section.

**Comment by bennytheg** [comment]
i'll ask on discord, i'll fr you
